on:
  push:
    branches:
      - master

      
name: Build documentation

jobs:
  doxygenator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # - name: Add Pretty CSS
    #   uses: wei/wget@v1
    #   with:
    #     args: -O wasm/docs/doxygen-awesome.css https://raw.githubusercontent.com/jothepro/doxygen-awesome-css/main/doxygen-awesome.css
    
    # - name: Doxygen Action
    #   uses: mattnotmitt/doxygen-action@v1.1.0
    #   with:
    #     working-directory: wasm/docs/

    - name: Copy everything
      run: |
        mkdir gh-pages-staging
    # cp -r wasm/docs/html gh-pages-staging/wasm
        cp -r src gh-pages-staging/app
    
    - name: GH Pages Deployment
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: gh-pages-staging 
        target-folder: docs
        clean: true # Automatically remove deleted files from the deploy branch
